apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-k8s-deployment
  namespace: deployment1
spec:
  selector:
    matchLabels:
      app: angular-k8s-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: angular-k8s-deployment
    spec:
      containers:
      - name: angular-k8s-deployment
        image: fatmamrabet/angular-app:4eae2c7e5338bb76dc3bdc2342e22575e1a08cc1
        ports:
        - containerPort: 80