apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-service
  namespace: deployment1
  labels:
    name: angular-k8s-deployment
spec:
  ports:
    - nodePort: 30170
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular-k8s-deployment
  type: NodePort